import { BackendConfig } from "./backendConfig";
import { FrontendConfig } from "./frontendConfig";

export interface NodeConfig {
  nodeId: string;
  frontendConfig: FrontendConfig;
  backendConfig: BackendConfig;
}

/** Resulting config from sync that concatenate response from backend and data from MSB scripts */
export interface NodeConfig_Sync extends FrontendConfig, NodeConfig_MSB {}

/** Config file generated by MSB script in /data/infoscreen/config/node.json */
export interface NodeConfig_MSB {
  /** MSB Node ID */
  msbNodeName: string;

  /** Maintenance mode status */
  maintenanceMode: boolean;
  /** Maintenance mode planned end date - Format ISO YYYY-MM-DD HH:mm */
  maintenanceEndDate: string;

  /** Backend origin (protocol + hostname) without ending slash /  */
  azureFunctionEndpoint: string;

  /** Tags assigned to the running MSB node, all tags start with an # */
  nodeTags: string[];
}
