export enum Api {
  customJobOffer = "customJobOffer",
  ideabox = "ideabox",
  iotHub = "iotHub",
  joboffers = "jobOffers",
  microservicebus = "microservicebus",
  newsInternal = "newsInternal",
  newsPublic = "newsPublic",
  openWeather = "openWeather",
  publicTransport = "publicTransport",
  sociabble = "sociabble",
  twentyMin = "twentyMin",
  twitter = "twitter",
  university = "university",
  uptownArticle = "uptownArticle",
  uptownEvent = "uptownEvent",
  uptownMenu = "uptownMenu",
}
