export enum LocalCache {
  Config = "config",
  CustomJobOffer = "customjoboffer",
  Ideabox = "ideabox",
  InfoscreenMonitoring = "infoscreenmonitoring",
  JobOffers = "joboffers",
  NewsInternal = "newsinternal",
  NewsPublic = "newspublic",
  OpenWeather = "openweather",
  PublicTransport = "publictransport",
  Sociabble = "sociabble",
  TwentyMin = "twentymin",
  Twitter = "twitter",
  University = "university",
  UptownArticle = "uptownarticle",
  UptownEvent = "uptownevent",
  UptownMenu = "uptownmenu",
}
