export enum LocalCacheFileName {
  Config = "config.json",
  CustomJobOffer = "custom-job-offer.json",
  Ideabox = "ideabox.json",
  InfoscreenMonitoring = "infoscreens-state.json",
  JobOffers = "job-offers.json",
  NewsInternal = "news-internal.json",
  NewsPublic = "news-public.json",
  OpenWeather = "openweather.json",
  PublicTransport = "public-transport.json",
  Sociabble = "sociabble.json",
  TwentyMin = "twentymin.json",
  Twitter = "twitter.json",
  University = "university.json",
  UptownArticle = "uptown-article.json",
  UptownEvent = "uptown-event.json",
  UptownMenu = "uptown-menu.json",
}
