export enum Slide {
  Coffee = "coffee",
  CustomJobOffer = "customjoboffer",
  Ideabox = "ideabox",
  Iframe = "iframe",
  InfoscreenMonitoring = "infoscreenmonitoring",
  JobOffers = "joboffers",
  LocalVideo = "localvideo",
  Maintenance = "maintenance",
  MonitoringIframe = "monitoringiframe",
  NewsInternal = "newsinternal",
  NewsPublic = "newspublic",
  PublicTransport = "publictransport",
  Sociabble = "sociabble",
  Spotlight = "spotlight",
  Stock = "stock",
  Traffic = "traffic",
  TwentyMin = "twentymin",
  Twitter = "twitter",
  University = "university",
  UniversityOverview = "universityoverview",
  UptownArticle = "uptownarticle",
  UptownEvent = "uptownevent",
  UptownMenu = "uptownmenu",
  Youtube = "youtube",
  WeatherDaily = "weatherdaily",
  WeatherWeekly = "weatherweekly",
}
